version: '3.8'

services:
  flask-app:
    image: personal-api:latest
    container_name: sivarajesh_container
    ports:
      - "5010:5000"  
    restart: always

  bhuvi:
    image: dharaneesh1318/personal-api:latest
    container_name: dharaneesh_container
    ports:
      - "5001:5000"  
    restart: always
